#!/usr/bin/env python3
"""One-off: draw tests/audio_mix_test.ppm — a 96x96 P6 launcher icon.

Three overlapping waves summing into one, which is what the mix bus does.  Pure
stdlib: PIL is available in WSL but a 96x96 P6 needs nothing.  Kept beside the
other generated assets so the icon can be regenerated rather than reverse
engineered; the shipped icons are IrfanView exports and there is no other
generator in the tree to follow.
"""
import math
import struct
import sys

W = H = 96
BG = (14, 16, 26)
WAVES = [
    # (freq cycles across the icon, amplitude px, centre y, colour)
    (1.5, 15, 30, (110, 90, 200)),
    (3.0, 11, 52, (70, 150, 190)),
    (5.0, 8, 70, (230, 170, 60)),
]
SUM_COLOR = (120, 235, 150)

px = [[BG for _ in range(W)] for _ in range(H)]


def plot(x, y, c):
    if 0 <= x < W and 0 <= y < H:
        px[y][x] = c


for x in range(W):
    t = x / (W - 1)
    for freq, amp, cy, col in WAVES:
        y = cy - amp * math.sin(2 * math.pi * freq * t)
        plot(x, int(round(y)), col)
        plot(x, int(round(y)) + 1, tuple(v * 3 // 5 for v in col))

    # The sum, clamped into its own band at the bottom — the bus itself.
    s = sum(amp * math.sin(2 * math.pi * freq * t) for freq, amp, _, _ in WAVES)
    s = max(-16, min(16, s))
    ys = 88 - s
    plot(x, int(round(ys)), SUM_COLOR)
    plot(x, int(round(ys)) + 1, tuple(v * 3 // 5 for v in SUM_COLOR))

# Frame, so the tile reads as a tile.
for x in range(W):
    plot(x, 0, (60, 66, 84)); plot(x, H - 1, (60, 66, 84))
for y in range(H):
    plot(0, y, (60, 66, 84)); plot(W - 1, y, (60, 66, 84))

out = sys.argv[1] if len(sys.argv) > 1 else "tests/audio_mix_test.ppm"
with open(out, "wb") as f:
    f.write(b"P6\n# Generated by tests/make_mix_icon.py\n%d %d\n255\n" % (W, H))
    for row in px:
        for r, g, b in row:
            f.write(struct.pack("BBB", r, g, b))
print("wrote", out)
