#!/bin/bash
#
# lib/rw-state.sh — which of a unit's files are PER-UNIT STATE, and which of them
# may go onto a card image.
#
# SOURCED, not executed:   . "$SCRIPT_DIR/lib/rw-state.sh"
#
# ONE home for two lists that used to exist only as a literal inside
# rootfs/fetch-card-parts.sh's remote heredoc:
#
#   BACKUP  everything that makes this unit THIS unit — settings, calibration,
#           pairings, high scores, SSH identity, and the operator's own private
#           config (the VNC password, ScummVM's ini and saves). Read by
#           commissioning/backup.sh; commissioning/restore.sh writes it back.
#
#   IMAGE   the subset a card image may carry (rootfs/fetch-card-parts.sh builds
#           state.tar from it). It is the BACKUP set minus:
#             - opt/vnc_client/vnc_client.conf   plaintext VNC password
#             - opt/games/scummvm.ini            the operator's ScummVM config
#             - ScummVM saves, and any game data under opt/games/scumm (copyrighted)
#             - loose files in /home/root and at / (where the saves land, below)
#             - etc/touch_calibration.conf.bak*  history, not state
#             - etc/hosts                        the vendor's, "Generated by PV
#                                                networkmanager"; make-card-image.sh
#                                                derives ours from etc/hostname
#             - home/root/data/**                p2, which the image creates EMPTY;
#                                                a copy in p6 would sit hidden
#                                                under p2's mount point
#
# ── Where ScummVM's saves go ────────────────────────────────────────────────
#
# Our backend constructs a bare DefaultSaveFileManager (backend-files/roomwizard.cpp)
# and registers no default "savepath"; scummvm.ini on the units sets none either.
# DefaultSaveFileManager::getSavePath() then returns "", which resolves against the
# process's CURRENT DIRECTORY: "/" when booted (the init script does not cd and
# app_launcher does not chdir), /home/root when started from an SSH shell. That is
# why a save, kq2.000, turned up loose in /home/root. Saves have no fixed name
# (<target>.NNN for AGI, <target>.sNN for SCUMM), so the backup takes every regular
# file directly in those two directories (RW_STATE_LOOSE_DIRS).
#
# ── The deny check is an ALLOWLIST, plus a hard list ────────────────────────
#
# rw_state_image_deny prints every tar entry that is not inside the IMAGE set —
# fail closed, so a file nobody thought about is refused rather than shipped — and
# additionally every entry matching RW_STATE_NEVER_IN_IMAGE, so that adding one of
# the forbidden paths to RW_STATE_IMAGE by mistake still cannot get it past the gate.
#
# rw_state_backup_foreign is the restore side's gate: every entry outside the BACKUP
# set, so restore.sh cannot be made to write /etc/shadow from a hand-built archive.
#
# Paths are relative to /, never absolute, and contain no whitespace (a name with
# whitespace is refused by the callers, as fetch-card-parts.sh always did).

# Exact paths, file or directory. A directory carries everything under it.
RW_STATE_IMAGE=(
    etc/hostname
    etc/timezone
    etc/localtime
    etc/touch_calibration.conf
    etc/input_config.conf
    opt/games/rw_config.conf
    opt/roomwizard/default-app
    var/lib/alsa/asound.state
    var/lib/bluetooth
    var/lib/bluealsa
    home/root/.ssh
)

# Backup-only paths. Globs are expanded by the device's shell.
RW_STATE_BACKUP_ONLY=(
    etc/hosts
    'etc/touch_calibration.conf.bak*'
    opt/vnc_client/vnc_client.conf
    opt/games/scummvm.ini
    'home/root/data/*.hig'
    home/root/data/ssh
)

# Directories whose loose REGULAR files are backed up (ScummVM saves; see above).
# "." is / itself. uImage-* in /home/root is a staged kernel, not state.
RW_STATE_LOOSE_DIRS=(home/root .)

# Never on an image, whatever RW_STATE_IMAGE says. Case globs; '*' crosses '/'.
RW_STATE_NEVER_IN_IMAGE=(
    'opt/vnc_client/vnc_client.conf'
    'opt/games/scummvm.ini'
    'opt/games/scumm' 'opt/games/scumm/*'
    'etc/hosts'
    'etc/touch_calibration.conf.bak*'
    'home/root/data' 'home/root/data/*'
)

# rw_state_lister <image|backup>
#   Prints a POSIX sh script (it runs under BusyBox ash on the unit) that lists,
#   one per line and relative to /, the members of the set that EXIST there. A
#   symlink such as etc/localtime is listed as itself (-L), so tar archives the
#   link. Exit 2 on an unknown set.
rw_state_lister() {
    local set="$1" paths d
    case "$set" in
        image)  paths="${RW_STATE_IMAGE[*]}" ;;
        backup) paths="${RW_STATE_IMAGE[*]} ${RW_STATE_BACKUP_ONLY[*]}" ;;
        *) echo "rw_state_lister: unknown set '$set' (image|backup)" >&2; return 2 ;;
    esac
    echo 'cd / || exit 1'
    # Unquoted on purpose: the globs in the list expand on the unit. A glob that
    # matches nothing stays literal and fails the -e test.
    printf 'for f in %s; do\n' "$paths"
    cat <<'REMOTE'
    if [ -e "$f" ] || [ -L "$f" ]; then echo "$f"; fi
done
REMOTE
    [ "$set" = backup ] || return 0
    for d in "${RW_STATE_LOOSE_DIRS[@]}"; do
        if [ "$d" = . ]; then printf 'for f in *; do\n'; else printf 'for f in %s/*; do\n' "$d"; fi
        cat <<'REMOTE'
    case "$f" in home/root/uImage-*) continue ;; esac
    if [ -f "$f" ] && [ ! -L "$f" ]; then echo "$f"; fi
done
REMOTE
    done
}

# rw_state_unsafe_paths
#   stdin: a tar listing (tar -tf). Prints every entry that is absolute or has a
#   '..' component. Exit 1 if it printed any, 0 if none.
rw_state_unsafe_paths() {
    local e found=1
    while IFS= read -r e; do
        case "/$e/" in
            //*|*/../*) printf '%s\n' "$e"; found=0 ;;
        esac
    done
    [ "$found" -ne 0 ]
}

# _rw_state_norm ENTRY — strip a leading "./" and a trailing "/".
_rw_state_norm() {
    local e="$1"
    while [ "${e#./}" != "$e" ]; do e="${e#./}"; done
    e="${e%/}"
    printf '%s' "$e"
}

# rw_state_image_allowed ENTRY — 0 if a tar entry may be on an image.
# The NEVER patterns are globs by design, hence the unquoted case pattern.
# shellcheck disable=SC2254
rw_state_image_allowed() {
    local raw="$1" e p
    case "/$raw/" in //*|*/../*) return 1 ;; esac
    e="$(_rw_state_norm "$raw")"
    case "$e" in ''|.) return 0 ;; esac      # the "./" entry itself
    for p in "${RW_STATE_NEVER_IN_IMAGE[@]}"; do
        case "$e" in $p) return 1 ;; esac
    done
    for p in "${RW_STATE_IMAGE[@]}"; do
        [ "$e" = "$p" ] && return 0
        case "$e" in "$p"/*) return 0 ;; esac
        # An ancestor directory of an allowed path (tar lists them when given one).
        case "$raw" in */) case "$p" in "$e"/*) return 0 ;; esac ;; esac
    done
    return 1
}

# rw_state_image_deny
#   stdin: a tar listing (tar -tf). Prints every entry NOT allowed on a card image,
#   one per line, as listed. Exit 1 if it printed any, 0 if the listing is clean.
#   The caller must check tar's own exit status: an empty listing is clean.
rw_state_image_deny() {
    local e found=1
    while IFS= read -r e; do
        [ -n "$e" ] || continue
        if ! rw_state_image_allowed "$e"; then printf '%s\n' "$e"; found=0; fi
    done
    [ "$found" -ne 0 ]
}

# _rw_state_backup_member ENTRY — 0 if a tar entry belongs to the BACKUP set.
# Patterns are globs by design, hence the unquoted case patterns.
# shellcheck disable=SC2254
_rw_state_backup_member() {
    local raw="$1" e p d
    case "/$raw/" in //*|*/../*) return 1 ;; esac
    e="$(_rw_state_norm "$raw")"
    case "$e" in ''|.) return 0 ;; esac
    for p in "${RW_STATE_IMAGE[@]}" "${RW_STATE_BACKUP_ONLY[@]}"; do
        case "$e" in $p|$p/*) return 0 ;; esac
        case "$raw" in */) case "$p" in "$e"/*) return 0 ;; esac ;; esac
    done
    # A loose file: a non-directory entry directly inside one of the loose dirs.
    case "$raw" in */) return 1 ;; esac
    for d in "${RW_STATE_LOOSE_DIRS[@]}"; do
        if [ "$d" = . ]; then
            case "$e" in */*) ;; *) return 0 ;; esac
        else
            case "$e" in "$d"/*/*) ;; "$d"/*) return 0 ;; esac
        fi
    done
    return 1
}

# rw_state_backup_foreign
#   stdin: a tar listing. Prints every entry outside the BACKUP set, unsafe ones
#   included — what commissioning/restore.sh refuses to write. Exit 1 if it printed
#   any, 0 if none.
rw_state_backup_foreign() {
    local e found=1
    while IFS= read -r e; do
        [ -n "$e" ] || continue
        if ! _rw_state_backup_member "$e"; then printf '%s\n' "$e"; found=0; fi
    done
    [ "$found" -ne 0 ]
}
