#!/usr/bin/env python3
"""Generate the nine 96x96 PPM (P6) control-panel icons for device_tools.

Outputs (written to icons/ next to this script, regardless of cwd):
  cp_audio cp_display cp_touch cp_led cp_usb cp_bluetooth cp_network
  cp_monitor cp_info  (.ppm)

Run (WSL, needs PIL):  python3 gen_cp_icons.py
The .ppm files are generated by this script (our own art, no third-party
assets, no fonts). Output is deterministic. native_apps/build-and-deploy.sh
copies icons/*.ppm to /opt/roomwizard/icons/, where device_tools loads them.
"""
import math
import os
from PIL import Image, ImageDraw

N = 96
SS = 4                      # supersampling factor
S = N * SS
WHITE = (255, 255, 255)
BORDER = (45, 45, 60)      # = icon_grid.c TILE_BG, so the corners vanish into the tile


def P(v):
    return int(round(v * SS))


def base(accent):
    im = Image.new("RGB", (S, S), BORDER)
    d = ImageDraw.Draw(im)
    d.rounded_rectangle([P(3), P(3), P(92), P(92)], radius=P(16), fill=accent)
    # subtle darker lower half for depth
    return im, d


def line(d, pts, w, fill=WHITE):
    pts = [(P(x), P(y)) for x, y in pts]
    d.line(pts, fill=fill, width=P(w), joint="curve")
    for x, y in (pts[0], pts[-1]):
        r = P(w) / 2
        d.ellipse([x - r, y - r, x + r, y + r], fill=fill)


def arc(d, cx, cy, r, a0, a1, w, fill=WHITE):
    pts = []
    for i in range(25):
        a = math.radians(a0 + (a1 - a0) * i / 24)
        pts.append((cx + r * math.cos(a), cy + r * math.sin(a)))
    line(d, pts, w, fill)


def circ(d, cx, cy, r, fill=None, outline=None, w=0):
    d.ellipse([P(cx - r), P(cy - r), P(cx + r), P(cy + r)], fill=fill,
              outline=outline, width=P(w))


def poly(d, pts, fill=WHITE):
    d.polygon([(P(x), P(y)) for x, y in pts], fill=fill)


def rrect(d, x0, y0, x1, y1, r, fill=None, outline=None, w=0):
    d.rounded_rectangle([P(x0), P(y0), P(x1), P(y1)], radius=P(r), fill=fill,
                        outline=outline, width=P(w))


def audio():
    im, d = base((200, 90, 30))
    poly(d, [(18, 40), (30, 40), (46, 26), (46, 70), (30, 56), (18, 56)])
    for r in (12, 22, 32):
        arc(d, 46, 48, r, -48, 48, 5)
    return im


def display():
    acc = (30, 120, 190)
    im, d = base(acc)
    rrect(d, 14, 20, 82, 66, 6, fill=WHITE)
    rrect(d, 19, 25, 77, 61, 3, fill=(20, 60, 110))
    poly(d, [(42, 66), (54, 66), (58, 78), (38, 78)])
    rrect(d, 30, 76, 66, 81, 2, fill=WHITE)
    circ(d, 48, 43, 7, fill=(255, 220, 60))
    for i in range(8):
        a = math.radians(i * 45)
        line(d, [(48 + 11 * math.cos(a), 43 + 11 * math.sin(a)),
                 (48 + 15 * math.cos(a), 43 + 15 * math.sin(a))], 3,
             (255, 220, 60))
    return im


def touch():
    im, d = base((130, 60, 170))
    for r in (30, 20):
        arc(d, 38, 30, r, 0, 360, 3, (225, 190, 240))
    # pointing hand: index finger, palm, curled fingers
    rrect(d, 32, 26, 44, 62, 6, fill=WHITE)            # index finger
    rrect(d, 22, 52, 70, 84, 12, fill=WHITE)           # palm
    rrect(d, 44, 46, 54, 62, 5, fill=WHITE)
    rrect(d, 54, 49, 64, 65, 5, fill=WHITE)
    rrect(d, 62, 54, 72, 70, 5, fill=WHITE)
    for x in (44, 54, 62):                              # finger gaps
        line(d, [(x, 54), (x, 62)], 1.5, (130, 60, 170))
    circ(d, 38, 26, 3, fill=(255, 230, 120))
    return im


def led():
    im, d = base((30, 150, 90))
    glow = (150, 235, 185)
    for i in range(9):
        a = math.radians(-180 + i * 22.5 + 11)
        line(d, [(48 + 26 * math.cos(a), 38 + 26 * math.sin(a)),
                 (48 + 33 * math.cos(a), 38 + 33 * math.sin(a))], 3.5, glow)
    # LED dome + flange + legs
    rrect(d, 32, 26, 64, 70, 16, fill=(255, 250, 200))
    rrect(d, 28, 56, 68, 66, 3, fill=(255, 250, 200))
    circ(d, 48, 40, 7, fill=WHITE)
    rrect(d, 39, 66, 44, 86, 1, fill=WHITE)
    rrect(d, 52, 66, 57, 80, 1, fill=WHITE)
    return im


def usb():
    im, d = base((50, 60, 80))
    acc = (90, 200, 255)
    line(d, [(14, 48), (82, 48)], 5, acc)
    poly(d, [(86, 48), (74, 40), (74, 56)], acc)
    circ(d, 14, 48, 7, fill=acc)
    line(d, [(30, 48), (42, 28), (60, 28)], 4, acc)
    rrect(d, 58, 23, 70, 33, 1, fill=acc)
    line(d, [(40, 48), (50, 66), (62, 66)], 4, acc)
    circ(d, 64, 66, 6, fill=acc)
    return im


def bluetooth():
    im, d = base((25, 80, 200))
    line(d, [(32, 34), (64, 62), (48, 76), (48, 20), (64, 34), (32, 62)], 7)
    return im


def network():
    im, d = base((20, 140, 150))
    cx, cy, r = 48, 48, 32
    circ(d, cx, cy, r, outline=WHITE, w=4)
    arc(d, cx, cy, r, 0, 360, 0.1)
    # meridians & parallels
    d.ellipse([P(cx - 14), P(cy - r), P(cx + 14), P(cy + r)], outline=WHITE,
              width=P(3))
    line(d, [(cx, cy - r), (cx, cy + r)], 3)
    line(d, [(cx - r, cy), (cx + r, cy)], 3)
    for dy in (-16, 16):
        hw = math.sqrt(r * r - dy * dy)
        line(d, [(cx - hw, cy + dy), (cx + hw, cy + dy)], 3)
    return im


def monitor():
    im, d = base((190, 60, 70))
    rrect(d, 12, 16, 84, 80, 6, fill=(60, 20, 30))
    for y in (32, 48, 64):
        line(d, [(18, y), (78, y)], 1.5, (130, 60, 70))
    line(d, [(18, 66), (32, 50), (42, 58), (54, 30), (66, 44), (78, 24)], 4.5,
         (255, 235, 120))
    circ(d, 78, 24, 4, fill=WHITE)
    return im


def info():
    im, d = base((200, 140, 20))
    circ(d, 48, 48, 34, fill=WHITE)
    circ(d, 48, 29, 5.5, fill=(200, 140, 20))
    rrect(d, 42, 40, 54, 70, 3, fill=(200, 140, 20))
    rrect(d, 38, 40, 50, 46, 2, fill=(200, 140, 20))
    rrect(d, 37, 65, 59, 71, 2, fill=(200, 140, 20))
    return im


ICONS = [("cp_audio", audio), ("cp_display", display), ("cp_touch", touch),
         ("cp_led", led), ("cp_usb", usb), ("cp_bluetooth", bluetooth),
         ("cp_network", network), ("cp_monitor", monitor), ("cp_info", info)]


def clip(im):
    m = Image.new("L", (S, S), 0)
    ImageDraw.Draw(m).rounded_rectangle([P(3), P(3), P(92), P(92)], radius=P(16), fill=255)
    bg = Image.new("RGB", (S, S), BORDER)
    bg.paste(im, (0, 0), m)
    return bg


def main():
    out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "icons")
    os.makedirs(out, exist_ok=True)
    for name, fn in ICONS:
        im = clip(fn()).resize((N, N), Image.LANCZOS)
        with open(os.path.join(out, name + ".ppm"), "wb") as f:
            f.write(b"P6\n%d %d\n255\n" % (N, N))
            f.write(im.tobytes())
    print("wrote %d icons to %s" % (len(ICONS), out))


if __name__ == "__main__":
    main()
